version: '3'

services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repair-matching-platform
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  nsetjsBackend:
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: repair-matching-platform
      DB_HOST: postgres
      POSTGRES_HOST: postgres

      REACT_URL : http://localhost:3000
      NEST_URL : http://localhost:8000
      JWT_SECRET : hard_to_guess_token_123
      JWT_SECRET : tryMe

      NODE_ENV: test
      PORT: 8000
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'matching-platform:latest'
    ports:
      - '8000:8000'
