version: '3'

services:
    tic-tac-toe:
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tic-tac-toe
            POSTGRES_HOST: postgres
            NODE_ENV: production
            PORT: 8080
        depends_on: 
            - postgres
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: "teckyio/tic-tac-toe:latest"
        ports:
            - "8080:8080"
    postgres:
        image: "postgres:13"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tic-tac-toe
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data