version: '3'

services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repair-matching-platform
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  nsetjsBackend:
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: repair-matching-platform
      DB_HOST: postgres
      POSTGRES_HOST: postgres

      REACT_URL : http://localhost:8100
      GOOGLE_APPLICATION_CREDENTIALS : "./google_api_key/eastern-thinker-361503-923321a085d0.json"
      
      NODE_ENV: test
      PORT: 8000
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'lokyin2004/matching-platform:V15'
    ports:
      - '8000:8000'
